# Generated by Django 5.0.4 on 2024-05-01 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_type'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Себестоимость сделки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость сделки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сделки')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения сделки')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сделки')),
                ('deal_statuses', models.CharField(choices=[('1', 'Новая сделка'), ('2', 'Выявлена потребность'), ('3', 'Формируется наше предложение'), ('4', 'Предложение сформировано, разрабатываем КП'), ('5', 'КП направлено на рассмотрение заказчику'), ('6', 'Согласование условий'), ('7', 'КП согласовано, подготавливаем договор'), ('8', 'Согласование договора обеими сторонами'), ('9', 'Договор направлен на подпись'), ('10', 'Договор подписан'), ('11', 'Направлен счет'), ('12', 'Счет оплачен, передано в работу'), ('13', 'В работе'), ('14', 'Сделка завершена успешно. Акты подписаны.'), ('15', 'Сделка завершена без успеха'), ('16', 'Архив')], max_length=2, verbose_name='Состояние сделки')),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер договора')),
                ('contract_image', models.ImageField(upload_to='documents_copy/contracts/Y.M.d/', verbose_name='Скан договора')),
                ('act_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер акта')),
                ('act_image', models.ImageField(blank=True, null=True, upload_to='documents_copy/acts/Y.M.d/', verbose_name='Скан акта')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_deals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='clients.client', verbose_name='Организация')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
