# Generated by Django 5.0.4 on 2024-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='deal_statuses',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='deal',
            name='act_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/documents_copy/acts/%Y/%m/%d/', verbose_name='Скан акта'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_image',
            field=models.ImageField(upload_to='uploads/documents_copy/contracts/%Y/%m/%d/', verbose_name='Скан договора'),
        ),
    ]
