# Generated by Django 5.0.4 on 2024-05-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_contract_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('1', 'Новая сделка, потребность не определена.'), ('2', 'Выявлена потребность'), ('3', 'Формируется наше предложение'), ('4', 'Предложение сформировано, разрабатываем КП'), ('5', 'КП направлено на рассмотрение заказчику'), ('6', 'Согласование условий'), ('7', 'КП согласовано, подготавливаем договор'), ('8', 'Согласование договора обеими сторонами'), ('9', 'Договор направлен на подпись'), ('10', 'Договор подписан'), ('11', 'Направлен счет'), ('12', 'Счет оплачен, передано в работу'), ('13', 'В работе'), ('14', 'Сделка завершена успешно. Акты подписаны.'), ('15', 'Сделка завершена без успеха'), ('16', 'Архив')], max_length=2, verbose_name='Состояние сделки'),
        ),
        migrations.CreateModel(
            name='CommentForDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deals.deal', verbose_name='Сделка')),
            ],
        ),
    ]
