# Generated by Django 5.0.4 on 2024-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_status_commentfordeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Общее описание сделки'),
        ),
    ]
