# Generated by Django 5.0.4 on 2024-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_rename_plantforrequestprice_plantforpricerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='comment_from_director',
            field=models.TextField(default='no', verbose_name='Комментарий от руководителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='comment_from_manager',
            field=models.TextField(default='no', verbose_name='Комментарий от менеджера'),
            preserve_default=False,
        ),
    ]
