# Generated by Django 5.0.4 on 2024-05-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_pricerequest_comment_from_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequest',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидание оценки'), ('2', 'Оценка завершена')], default='1', max_length=1, verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('1', 'Новая сделка.\nНеобходимо выбрать услугу.'), ('2', 'Выявлена потребность. Необходимо запросить стоимость у руководителя.'), ('3', 'Запрос стоимости отправлен. Ожидание ответа руководителя.'), ('4', 'Предложение сформировано, разрабатываем КП'), ('5', 'КП направлено на рассмотрение заказчику'), ('6', 'Согласование условий'), ('7', 'КП согласовано, подготавливаем договор'), ('8', 'Согласование договора обеими сторонами'), ('9', 'Договор направлен на подпись'), ('10', 'Договор подписан'), ('11', 'Счет направлен заказчику. Контроль оплаты.'), ('12', 'Счет оплачен, передано в работу'), ('13', 'В работе'), ('14', 'Сделка завершена успешно. Акты подписаны.'), ('15', 'Сделка завершена без успеха'), ('16', 'Архив')], max_length=2, verbose_name='Состояние сделки'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_request', to='deals.deal', verbose_name='Сделка'),
        ),
    ]
