# Generated by Django 5.0.4 on 2024-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_pricerequest_status_alter_deal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='commercial_offer',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/documents_copy/commercial_offer/%Y/%m/%d/', verbose_name='Коммерческое предложение'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('1', 'Новая сделка.\nНеобходимо выбрать услугу.'), ('2', 'Выявлена потребность. Необходимо запросить стоимость у руководителя.'), ('3', 'Запрос стоимости отправлен. Ожидание ответа руководителя.'), ('4', 'Стоимость утверждена. Необходимо отправить КП клиенту.'), ('5', 'КП направлено. Ведутся переговоры.'), ('6', 'Согласование условий'), ('7', 'КП согласовано, подготавливаем договор'), ('8', 'Согласование договора обеими сторонами'), ('9', 'Договор направлен на подпись'), ('10', 'Договор подписан'), ('11', 'Счет направлен заказчику. Контроль оплаты.'), ('12', 'Счет оплачен, передано в работу'), ('13', 'В работе'), ('14', 'Сделка завершена успешно. Акты подписаны.'), ('15', 'Сделка завершена без успеха'), ('16', 'Архив')], max_length=2, verbose_name='Состояние сделки'),
        ),
    ]
