# Generated by Django 5.0.4 on 2024-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_remove_deal_commercial_offer_alter_deal_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialoffer',
            old_name='title',
            new_name='number',
        ),
    ]
