# Generated by Django 5.0.4 on 2024-06-03 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_alter_deal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialoffer',
            options={'verbose_name': 'Коммерческое предложение', 'verbose_name_plural': 'Коммерческие предложения'},
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='counter_number',
            field=models.PositiveIntegerField(default=1, verbose_name='№'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_offers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialoffer',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='№ исх.'),
        ),
    ]
