# Generated by Django 5.0.4 on 2024-06-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_alter_commercialoffer_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_offers', to='deals.deal', verbose_name='Сделка'),
        ),
    ]
