# Generated by Django 5.0.4 on 2024-06-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_alter_deal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Запрос создан')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_requests', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_requests', to='deals.deal', verbose_name='Запрос контракта')),
            ],
            options={
                'verbose_name': 'Запрос контракта',
                'verbose_name_plural': 'Запросы контрактов',
            },
        ),
    ]
