# Generated by Django 5.0.4 on 2024-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_contractrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='description',
            field=models.TextField(default='text', verbose_name='Описание условий договора'),
            preserve_default=False,
        ),
    ]
