# Generated by Django 5.0.4 on 2024-06-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_remove_deal_contract_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Выставлен, но не подписан'), ('2', 'Подписан')], default='1', max_length=2, verbose_name='Статус')),
                ('act_number', models.CharField(max_length=155, verbose_name='Номер акта')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('act_text', models.FileField(blank=True, null=True, upload_to='uploads/documents_copy/act_texts/%Y/%m/%d/', verbose_name='Текст акта')),
                ('act_image', models.FileField(blank=True, null=True, upload_to='uploads/documents_copy/act_texts/%Y/%m/%d/', verbose_name='Копия подписанного акта')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='act',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='act', to='deals.act', verbose_name='Акт'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Выставлен, не оплачен'), ('2', 'Оплачен')], max_length=2, verbose_name='Статус')),
                ('bill_number', models.CharField(max_length=155, verbose_name='Номер счета')),
                ('bill_date', models.DateField(verbose_name='Дата счета')),
                ('bill_image', models.FileField(blank=True, null=True, upload_to='uploads/documents_copy/bill_images/%Y/%m/%d/', verbose_name='Копия счета')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='deals.contract', verbose_name='Договор')),
            ],
        ),
    ]
