# Generated by Django 5.0.4 on 2024-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_act_contract_act_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидание договора'), ('2', 'Проект договора готов')], default='1', max_length=2, verbose_name='Статус'),
        ),
    ]
