# Generated by Django 5.0.4 on 2024-06-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0025_contractrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='act',
        ),
        migrations.AddField(
            model_name='act',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act', to='deals.contract', verbose_name='Договор'),
        ),
    ]
