# Generated by Django 5.0.4 on 2024-06-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_remove_contract_act_act_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='deals.deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', 'Подготовка и согласование'), ('2', 'Внесение изменений'), ('3', 'Подписан обеими сторонами'), ('4', 'Оплачен и передан в работу')], max_length=2, verbose_name='Статус контракта'),
        ),
    ]
