# Generated by Django 5.0.4 on 2024-04-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Физ. лицо (без ИП'), ('2', 'ИП'), ('3', 'Самозанятый'), ('4', 'Организация (ООО, АО и т.д.)')], max_length=100, verbose_name='Тип')),
                ('type_of_activity', models.CharField(max_length=255, verbose_name='Род деятельности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Телефон организации')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='email организации')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('telephone', models.CharField(max_length=15, verbose_name='телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=15, verbose_name='whatsapp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='telegram')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='email')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person', to='clients.client', verbose_name='Организация')),
            ],
        ),
    ]
