# Generated by Django 5.0.4 on 2024-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_contactperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('1', 'Физ. лицо (без ИП)'), ('2', 'ИП'), ('3', 'Самозанятый'), ('4', 'Организация (ООО, АО и т.д.)')], max_length=100, verbose_name='Тип'),
        ),
    ]
