# Generated by Django 5.0.4 on 2024-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='telephone',
            field=models.CharField(max_length=25, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16, verbose_name='whatsapp'),
        ),
    ]
